const nodemailer = require("nodemailer");
const { Resend } = require("resend");
const logger = require("../config/logger");

// ── HTML template ─────────────────────────────────────────────────────────────
const buildHTML = (summary, filename, rowCount) => {
  const timestamp = new Date().toUTCString();
  const formatted = summary
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\n/g, "<br>");

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Sales Insight Report</title></head>
<body style="margin:0;padding:0;background:#0a0a0f;font-family:'Segoe UI',Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#0a0a0f;padding:40px 20px;">
  <tr><td align="center">
    <table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;">
      <tr><td style="background:linear-gradient(135deg,#1a1a2e,#16213e);border-radius:12px 12px 0 0;padding:36px 44px;border-bottom:2px solid #e8c547;">
        <div style="color:#e8c547;font-size:11px;font-weight:700;letter-spacing:3px;text-transform:uppercase;margin-bottom:8px;">Rabbitt AI</div>
        <h1 style="color:#fff;margin:0;font-size:26px;font-weight:300;">Sales Insight Report</h1>
        <p style="color:#8888aa;margin:8px 0 0;font-size:12px;">${timestamp}</p>
      </td></tr>
      <tr><td style="background:#13131f;padding:12px 44px;border-left:1px solid #1e1e30;border-right:1px solid #1e1e30;">
        <span style="color:#666688;font-size:12px;">📄 ${filename} · </span>
        <span style="color:#e8c547;font-size:12px;font-weight:600;">${rowCount.toLocaleString()} records analyzed</span>
      </td></tr>
      <tr><td style="background:#13131f;padding:32px 44px;border-left:1px solid #1e1e30;border-right:1px solid #1e1e30;">
        <div style="color:#ccccdd;font-size:15px;line-height:1.8;">${formatted}</div>
      </td></tr>
      <tr><td style="background:#0d0d18;border-radius:0 0 12px 12px;padding:20px 44px;border:1px solid #1e1e30;border-top:none;">
        <p style="color:#555566;font-size:11px;margin:0;">Auto-generated by <strong style="color:#e8c547;">Rabbitt AI Sales Insight Automator</strong>. Do not reply.</p>
      </td></tr>
    </table>
  </td></tr>
</table>
</body></html>`;
};

const buildPlainText = (summary, filename, rowCount) => `
RABBITT AI — SALES INSIGHT REPORT
Generated: ${new Date().toUTCString()}
Source: ${filename} (${rowCount} records)
${"=".repeat(60)}

${summary}

${"=".repeat(60)}
Auto-generated by Rabbitt AI Sales Insight Automator.
`.trim();

// ── Main export ───────────────────────────────────────────────────────────────
const sendSummaryEmail = async ({ recipient, summary, filename, rowCount }) => {
  const subject = `📊 Sales Insight Report — ${filename}`;
  const html = buildHTML(summary, filename, rowCount);
  const text = buildPlainText(summary, filename, rowCount);

  // ── 1. Gmail via service shortcut (works on Render — uses HTTPS internally) ─
  if (process.env.GMAIL_USER && process.env.GMAIL_APP_PASSWORD) {
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.GMAIL_USER,
        pass: process.env.GMAIL_APP_PASSWORD,
      },
    });

    const info = await transporter.sendMail({
      from: `"${process.env.FROM_NAME || "Rabbitt AI"}" <${process.env.GMAIL_USER}>`,
      to: recipient,
      subject,
      text,
      html,
    });

    logger.info(`📧 Email delivered via Gmail → ${recipient} | messageId: ${info.messageId}`);
    return true;
  }

  // ── 2. Brevo SMTP Relay fallback ──────────────────────────────────────────
  if (process.env.BREVO_API_KEY) {
    const transporter = nodemailer.createTransport({
      host: "smtp-relay.brevo.com",
      port: 587,
      secure: false,
      auth: {
        user: process.env.FROM_EMAIL,
        pass: process.env.BREVO_API_KEY,
      },
    });

    const info = await transporter.sendMail({
      from: `"${process.env.FROM_NAME || "Rabbitt AI"}" <${process.env.FROM_EMAIL}>`,
      to: recipient,
      subject,
      text,
      html,
    });

    logger.info(`📧 Email delivered via Brevo SMTP → ${recipient} | messageId: ${info.messageId}`);
    return true;
  }

  // ── 2. Resend fallback (only sends to signup email on free tier) ──────────
  if (process.env.RESEND_API_KEY) {
    const resend = new Resend(process.env.RESEND_API_KEY);
    const { data, error } = await resend.emails.send({
      from: `${process.env.FROM_NAME || "Rabbitt AI"} <onboarding@resend.dev>`,
      to: [recipient],
      subject,
      html,
      text,
    });

    if (error) {
      logger.error(`❌ Resend error: ${JSON.stringify(error)}`);
      throw new Error(error.message);
    }

    logger.info(`📧 Email delivered via Resend → ${recipient} | id: ${data.id}`);
    return true;
  }

  // ── 3. Dev fallback ───────────────────────────────────────────────────────
  logger.warn("No email provider configured — printing to console (dev mode).");
  logger.info(`\n${"=".repeat(60)}\n📧 [DEV] To: ${recipient}\nSubject: ${subject}\n${text}\n${"=".repeat(60)}`);
  return false;
};

module.exports = { sendSummaryEmail };
