const nodemailer = require("nodemailer");
const logger = require("../config/logger");

// ── Build transporter ─────────────────────────────────────────────────────────
const createTransporter = () => {
  // SendGrid via SMTP
  if (process.env.SENDGRID_API_KEY) {
    return nodemailer.createTransport({
      host: "smtp.sendgrid.net",
      port: 587,
      auth: {
        user: "apikey",
        pass: process.env.SENDGRID_API_KEY,
      },
    });
  }

  // Generic SMTP (Gmail, Outlook, etc.)
  if (process.env.SMTP_USER && process.env.SMTP_PASSWORD) {
    return nodemailer.createTransport({
      host: process.env.SMTP_HOST || "smtp.gmail.com",
      port: parseInt(process.env.SMTP_PORT || "587"),
      secure: false,
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASSWORD,
      },
    });
  }

  return null;
};

// ── HTML template ─────────────────────────────────────────────────────────────
const buildHTML = (summary, filename, rowCount) => {
  const timestamp = new Date().toUTCString();
  const formatted = summary
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\n/g, "<br>");

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Sales Insight Report</title></head>
<body style="margin:0;padding:0;background:#0a0a0f;font-family:'Segoe UI',Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#0a0a0f;padding:40px 20px;">
  <tr><td align="center">
    <table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;">
      <tr><td style="background:linear-gradient(135deg,#1a1a2e,#16213e);border-radius:12px 12px 0 0;padding:36px 44px;border-bottom:2px solid #e8c547;">
        <div style="color:#e8c547;font-size:11px;font-weight:700;letter-spacing:3px;text-transform:uppercase;margin-bottom:8px;">Rabbitt AI</div>
        <h1 style="color:#fff;margin:0;font-size:26px;font-weight:300;">Sales Insight Report</h1>
        <p style="color:#8888aa;margin:8px 0 0;font-size:12px;">${timestamp}</p>
      </td></tr>
      <tr><td style="background:#13131f;padding:12px 44px;border-left:1px solid #1e1e30;border-right:1px solid #1e1e30;">
        <span style="color:#666688;font-size:12px;">📄 ${filename} · </span>
        <span style="color:#e8c547;font-size:12px;font-weight:600;">${rowCount.toLocaleString()} records analyzed</span>
      </td></tr>
      <tr><td style="background:#13131f;padding:32px 44px;border-left:1px solid #1e1e30;border-right:1px solid #1e1e30;">
        <div style="color:#ccccdd;font-size:15px;line-height:1.8;">${formatted}</div>
      </td></tr>
      <tr><td style="background:#0d0d18;border-radius:0 0 12px 12px;padding:20px 44px;border:1px solid #1e1e30;border-top:none;">
        <p style="color:#555566;font-size:11px;margin:0;">Auto-generated by <strong style="color:#e8c547;">Rabbitt AI Sales Insight Automator</strong>. Do not reply.</p>
      </td></tr>
    </table>
  </td></tr>
</table>
</body></html>`;
};

const buildPlainText = (summary, filename, rowCount) => `
RABBITT AI — SALES INSIGHT REPORT
Generated: ${new Date().toUTCString()}
Source: ${filename} (${rowCount} records)
${"=".repeat(60)}

${summary}

${"=".repeat(60)}
Auto-generated by Rabbitt AI Sales Insight Automator.
`.trim();

// ── Main export ───────────────────────────────────────────────────────────────
const sendSummaryEmail = async ({ recipient, summary, filename, rowCount }) => {
  const transporter = createTransporter();
  const subject = `📊 Sales Insight Report — ${filename}`;
  const html = buildHTML(summary, filename, rowCount);
  const text = buildPlainText(summary, filename, rowCount);

  if (!transporter) {
    logger.warn("No email provider configured — logging to console (dev mode).");
    logger.info(`\n${"=".repeat(60)}\n📧 [DEV] To: ${recipient}\nSubject: ${subject}\n${text}\n${"=".repeat(60)}`);
    return false;
  }

  await transporter.sendMail({
    from: `"${process.env.FROM_NAME || "Rabbitt AI"}" <${process.env.FROM_EMAIL || process.env.SMTP_USER}>`,
    to: recipient,
    subject,
    text,
    html,
  });

  logger.info(`📧 Email delivered → ${recipient}`);
  return true;
};

module.exports = { sendSummaryEmail };
